import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = new URL('.', import.meta.url)
const read = (name) => readFileSync(new URL(name, root), 'utf8')
const assert = (condition, message) => { if (!condition) throw new Error(message) }
const manifest = JSON.parse(read('manifest.json'))
const development = JSON.parse(read('manifest.dev.json'))
const packageJson = JSON.parse(read('package.json'))

assert(manifest.version === development.version && manifest.version === packageJson.version, 'extension package versions must stay aligned')

for (const [name, value] of [['production', manifest], ['development', development]]) {
  assert(value.manifest_version === 3, `${name}: Manifest V3 is required`)
  assert(value.devtools_page === 'devtools.html', `${name}: missing DevTools entrypoint`)
  assert(value.side_panel?.default_path === 'panel.html', `${name}: missing shared side-panel UI`)
  assert(value.background?.service_worker === 'background.js', `${name}: missing service worker`)
  assert(value.icons?.['16'] === 'icons/qcg-16.png' && value.icons?.['128'] === 'icons/qcg-128.png', `${name}: final QCG identity icons are required`)
  assert(value.action?.default_icon?.['16'] === 'icons/qcg-16.png' && value.action?.default_icon?.['32'] === 'icons/qcg-32.png', `${name}: toolbar action must use the final QCG identity`)
  assert(value.permissions?.includes('sidePanel'), `${name}: sidePanel permission is required`)
  assert(value.permissions?.includes('storage'), `${name}: session-only panel state requires storage permission`)
  assert(Number(value.minimum_chrome_version) >= 142, `${name}: Chrome 142+ is required for close/onClosed side-panel lifecycle`)
  assert(!value.permissions?.includes('tabs') && !value.permissions?.includes('scripting'), `${name}: broad permissions are not allowed`)
  assert(value.content_scripts?.length === 2 && value.content_scripts[0].world === 'MAIN', `${name}: require MAIN and isolated bridge pair`)
}
assert(JSON.stringify(manifest.host_permissions) === JSON.stringify(['https://qcg.securedme.ca/*']), 'production: only qcg.securedme.ca may receive a bridge')
assert(development.host_permissions.includes('http://localhost:5173/*') && development.host_permissions.includes('http://127.0.0.1:5173/*'), 'development: local QCG hosts are required')

const background = read('background.js')
const pageBridge = read('pageBridge.js')
const panel = read('panel.js')
const panelHtml = read('panel.html')
for (const kind of ['human_review_disposition', 'human_memory_disposition', 'human_message', 'human_decision', 'gemini_manual_handoff_create', 'gemini_manual_reply_preview', 'gemini_manual_reply_import']) {
  assert(background.includes(`'${kind}'`) && pageBridge.includes(`'${kind}'`) && panel.includes(`'${kind}'`), `command ${kind} must be allowlisted end-to-end`)
}
for (const forbidden of ['run_bounded_local_simulation', 'consent', 'provider_calls', 'qpu_submission']) {
  assert(!background.includes(forbidden), `broker must not expose ${forbidden}`)
}
assert(pageBridge.includes('__QCG_CONSOLE_V2__') && pageBridge.includes('executeConsoleCommand') && pageBridge.includes('queueHumanReviewDisposition'), 'bridge must prefer v2 and retain collaboration-only v1 fallback')
assert(background.includes("value.schema_version !== 'qcg-console-command.v1'") && background.includes("value.kind === 'human_decision'"), 'commands require the v1 console schema and human decisions')
assert(panel.includes("kind: 'human_decision'") && panel.includes("available_commands"), 'human decisions must be explicit UI actions gated by v2 availability')
assert(panel.includes("qcg-console-devtools.v1") && panel.includes("qcg-console-side-panel.v1"), 'DevTools and side panel must share the console transport')
assert(!panelHtml.includes('id="open-companion"') && panelHtml.includes('id="access-toggle"') && panelHtml.includes('id="access-panel"'), 'the Companion must use its scarce header space for direct-use access controls, not a circular open button')
assert(panelHtml.includes('icons/inspector-q-avatar.jpg') && panelHtml.includes('Inspector Q observes bounded state; human authority remains explicit.'), 'Inspector Q must remain a decorative bounded-state observer, never an authority claim')
assert(read('devtools.js').includes("'icons/qcg-32.png'"), 'the F12 panel must use the final QCG identity icon')
assert(panel.includes('qcg-companion-access-v1') && panel.includes('applyAccessibility') && panel.includes('toggleAccess'), 'Companion access preferences must be local, persistent and keyboard-dismissible')
for (const profile of ['base', 'autism-calm', 'adhd-sprint', 'deep-work']) assert(panelHtml.includes(`data-access-profile="${profile}"`) && panel.includes(`'${profile}'`), `Companion Access must retain the SecuredMe ${profile} reading profile`)
assert(read('panel.css').includes('--control-edge') && read('panel.css').includes('button:hover { border-color: var(--cyan); }'), 'every Companion button needs a persistent warm edge that changes to cyan on hover')
assert(!panel.includes('inspectedWindow.eval') && panel.includes('QcgSnapshotSanitizer'), 'DevTools must consume the same sanitized broker snapshot as the side panel')
const contentBridge = read('contentBridge.js')
assert(manifest.content_scripts[1].js[0] === 'snapshotSanitizer.js' && development.content_scripts[1].js[0] === 'snapshotSanitizer.js', 'isolated content transport must load the strict snapshot sanitizer first')
assert(read('panel.html').includes('snapshotSanitizer.js'), 'the shared panel must sanitize every broker snapshot before rendering or copying')
assert(background.includes("importScripts('snapshotSanitizer.js')"), 'the background broker must sanitize before caching or routing')
assert(contentBridge.includes("qcg-console-extension-control.v1") && contentBridge.includes("type: 'open_companion_result'") && contentBridge.includes("[data-qcg-open-companion]") && contentBridge.includes('event.isTrusted'), 'page open-companion handshake must originate from a trusted marked click and return a paired result')
assert(contentBridge.includes("type: 'qcg-console-open-side-panel', request_id: requestId, action") && contentBridge.includes('validCompanionAction(action)') && !contentBridge.includes('tab_id: data.'), 'content bridge must forward only an explicit open/close action and never a page-supplied tab id')
assert(contentBridge.includes('onDisconnect.addListener') && contentBridge.includes('scheduleReconnect'), 'the page bridge must reconnect after losing its runtime port')
assert(contentBridge.includes("'unsupported_tab'"), 'the page bridge must preserve the bounded unsupported-tab diagnostic')
assert(panel.includes('onDisconnect.addListener') && panel.includes('scheduleReconnect'), 'side-panel and DevTools surfaces must reconnect after losing their runtime port')
assert(background.includes('const tabId = sender.tab?.id') && background.includes("message.type === 'qcg-console-open-side-panel'"), 'worker must derive the page handshake tab from sender.tab.id')
assert(background.includes('function prepareCompanion(tabId)') && background.includes('void prepareCompanion(tabId)'), 'side-panel options must be prepared when the content bridge attaches')
assert(background.includes('function disableDefaultCompanion()') && background.includes("setOptions({ enabled: false })"), 'the manifest default side panel must be disabled outside supported QCG tabs')
assert(background.includes('function disableCompanion(tabId)') && background.includes("setOptions({ tabId, enabled: false })"), 'a disconnected QCG tab must lose its side-panel surface')
assert(background.includes("clearSnapshot(tabId, 'page_bridge_disconnected')"), 'a disconnected page bridge must clear retained snapshots')
const openCompanionBody = background.slice(background.indexOf('async function openCompanion(tabId, action)'), background.indexOf('function deliverSnapshot'))
assert(openCompanionBody.includes('if (!contentPorts.has(tabId))'), 'companion opening must be rejected outside a connected QCG page')
assert(openCompanionBody.indexOf('chrome.sidePanel.open({ tabId })') < openCompanionBody.indexOf('chrome.tabs.create'), 'side-panel open must be the first browser operation in the user-gesture path')
assert(openCompanionBody.includes("action === 'close'") && openCompanionBody.includes('chrome.sidePanel.close({ tabId })') && openCompanionBody.includes("opened: 'side_panel_closed'"), 'Chrome 142+ must honor an explicit close action after worker suspension')
assert(!openCompanionBody.includes('chrome.sidePanel.setOptions'), 'side-panel setup must not consume the open gesture')
for (const label of ['Inspector', 'Console', 'WebMCP', 'Decisions', 'Sources', 'Receipts', 'Activity']) assert(panelHtml.includes(label), `shared console navigation missing ${label}`)
assert(read('panel.css').includes('--emerald') && read('panel.css').includes('--cyan') && read('panel.css').includes('--gold') && read('panel.css').includes('--red'), 'shared console requires semantic neutral color tokens')
console.log('QCG extension validation passed: MV3 manifests, restricted hosts, strict command allowlist, and v1/v2 bridge fallback.')
