import { useState, type ReactNode } from 'react'
import { bellOpenQasmProgram, bellProgram, demoCards } from '../catalog'
import { getQuantumAdapter, quantumAdapters } from '../quantumAdapters'
import type { QcgDebugMessage } from '../debugContracts'
import type { HumanChoice, QcgState, QuantumProfileId } from '../types'
import { parseConsoleLine } from './commandParser'
import type { ConsoleView } from './contracts'

const short = (value?: string) => value ? `${value.slice(0, 12)}…${value.slice(-8)}` : '—'
const download = (name: string, content: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }

interface ViewProps {
  view: ConsoleView; state: QcgState; selected: string; select(card: string): void; artifactProfileId: QuantumProfileId; setArtifactProfileId(id: QuantumProfileId): void; busy: boolean
  runDemo(): void; importArtifact(file: File): void; inspectImported(): void; setView(view: ConsoleView): void; recordDecision(choice: HumanChoice, justification: string): void; runSimulation(): void; revokeConsent(): void
  exportEvidence(format: 'json' | 'markdown'): void; toolNames: string[]; registrationStatus: string; supported: boolean; debugMessages: QcgDebugMessage[]; humanMessage(summary: string): void; storedReceipts: number
  actorFilter: string; kindFilter: string; setFilters(actor: string, kind: string): void; requestHandoff(intent: 'debug' | 'search' | 'find' | 'brainstorm' | 'decision'): Promise<string>
}

export function ConsoleInspector({ state, debugMessages, sessionId }: { state: QcgState; debugMessages: QcgDebugMessage[]; sessionId: string }) {
  const participants = [...new Map(debugMessages.map((message) => [`${message.actor}:${message.role}`, `${message.actor} · ${message.role}`])).values()]
  const openReviews = debugMessages.filter((message) => message.kind === 'decision_request' && message.status !== 'resolved').length
  const gemini = [...debugMessages].reverse().find((message) => message.actor === 'gemini')
  return <><div className="inspector-heading"><span className="status-pip technical" /><div><h2>Integrity</h2><small>session {sessionId.slice(0, 8)}</small></div></div><dl className="console-facts"><dt>Artifact digest</dt><dd><code>{short(state.manifest?.artifact_digest)}</code></dd><dt>Compiler</dt><dd>{state.manifest?.compiler.status ?? 'pending'}</dd><dt>Target</dt><dd>{state.targetProfile?.label ?? 'not selected'}</dd><dt>Recommendation</dt><dd>{state.recommendation?.decision.replaceAll('_', ' ') ?? 'pending'}</dd></dl><div className="inspector-section authority"><h3><span className="status-pip authority" /> Human authority</h3><dl className="console-facts"><dt>State</dt><dd>{state.authority_state}</dd><dt>Decision</dt><dd>{state.humanDecision?.choice ?? 'pending'}</dd><dt>Receipt</dt><dd><code>{short(state.receipt?.digest)}</code></dd></dl></div><div className="inspector-section"><h3>Effects</h3><div className="effect-chips">{Object.entries(state.effects).map(([name, value]) => <span key={name}>{name.replaceAll('_', ' ')} <b>{value}</b></span>)}</div></div><div className="inspector-section"><h3>Participants</h3><p className="participant-list">{participants.length ? participants.join(' · ') : 'No declared participants.'}</p><p className="muted">{openReviews} open review{openReviews === 1 ? '' : 's'} · Gemini {gemini ? gemini.status : 'not connected'}</p></div><p className="muted">Identifiers and bounded evidence only. Source, consent tokens, paths and provider credentials remain private.</p></>
}

export function ConsoleViews(props: ViewProps) {
  if (props.view === 'inspector') return <InspectorView {...props} />
  if (props.view === 'console') return <PaletteView {...props} />
  if (props.view === 'webmcp') return <WebMcpView {...props} />
  if (props.view === 'decisions') return <DecisionsView {...props} />
  if (props.view === 'sources') return <SourcesView />
  if (props.view === 'receipts') return <ReceiptsView {...props} />
  return <ActivityView {...props} />
}

function Heading({ kicker, title, children, tone = 'technical' }: { kicker: string; title: string; children: ReactNode; tone?: 'technical' | 'authority' | 'evidence' }) { return <header className={`view-heading ${tone}`}><p><span className="status-pip" />{kicker}</p><h1>{title}</h1>{children}</header> }
function InspectorView(props: ViewProps) {
  const adapter = getQuantumAdapter(props.artifactProfileId)!
  return <><Heading kicker="01 / bounded input" title="Inspector"><span>Import stays in browser memory; only bounded evidence crosses surfaces.</span></Heading><div className="console-grid two"><article className="console-card"><h2>Artifact intake</h2><label>Quantum profile<select value={props.artifactProfileId} onChange={(event) => props.setArtifactProfileId(event.target.value as QuantumProfileId)}>{quantumAdapters.map((item) => <option key={item.id} value={item.id}>{item.label} · {item.executable ? 'local executable' : 'inspection only'}</option>)}</select></label><p className="muted">{adapter.extensions.join(', ')} · 128 KiB maximum · {adapter.capabilities.simulate ? 'simulation capable' : 'static only'}</p><input aria-label="Quantum artifact file" type="file" accept={`${adapter.extensions.join(',')},text/plain`} disabled={props.busy} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) props.importArtifact(file) }} /><div className="button-row"><button onClick={() => download('qcg-bell.qs', bellProgram, 'text/plain')}>Q# Bell</button><button onClick={() => download('qcg-bell.qasm', bellOpenQasmProgram, 'text/plain')}>OpenQASM Bell</button><button disabled={props.busy || props.state.manifest?.provenance !== 'human_import'} onClick={props.inspectImported}>Inspect import</button></div></article><article className="console-card"><h2>Frozen decision cards</h2><div className="fixture-list">{demoCards.map((card) => <button className={props.selected === card.id ? 'selected' : ''} key={card.id} onClick={() => props.select(card.id)}><b>{card.title}</b><small>{card.detail}</small></button>)}</div><button className="primary wide" disabled={props.busy} onClick={props.runDemo}>Run selected preflight</button></article></div>{props.state.manifest && <article className="console-card"><h2>Current artifact</h2><dl className="console-facts"><dt>File</dt><dd>{props.state.manifest.file_name}</dd><dt>Profile</dt><dd>{props.state.manifest.artifact_profile}</dd><dt>Format</dt><dd>{props.state.manifest.format}</dd><dt>Digest</dt><dd><code>{short(props.state.manifest.artifact_digest)}</code></dd><dt>Compiler</dt><dd>{props.state.manifest.compiler.status}</dd></dl></article>}</>
}
function PaletteView(props: ViewProps) {
  const [line, setLine] = useState('')
  const [output, setOutput] = useState<string[]>([])
  const push = (message: string) => setOutput((current) => [...current, message].slice(-50))
  async function execute(): Promise<void> {
    const parsed = parseConsoleLine(line)
    setLine('')
    if (!parsed.ok) { push(`Rejected: ${parsed.error}`); return }
    const command = parsed.command
    if (command.kind === 'clear_view') { setOutput([]); return }
    if (command.kind === 'help') { push('help · inspect · evaluate · open <view> · filter actor=<actor> kind=<kind> · handoff <intent> · export receipt <json|markdown> · clear-view'); return }
    if (command.kind === 'inspect') { if (!props.state.manifest) push('Inspector: no artifact is loaded.'); else { props.inspectImported(); push('Inspector: bounded inspection requested.'); } return }
    if (command.kind === 'evaluate') { props.runDemo(); push('Evaluate: selected preflight requested.'); return }
    if (command.kind === 'open') { props.setView(command.view); push(`Opened ${command.view}.`); return }
    if (command.kind === 'filter') { props.setFilters(command.actor, command.messageKind); props.setView('activity'); push(`Activity filter: actor=${command.actor} kind=${command.messageKind}.`); return }
    if (command.kind === 'handoff') { push(await props.requestHandoff(command.intent)); return }
    props.exportEvidence(command.format); push(`Receipt ${command.format} export requested.`)
  }
  return <><Heading kicker="bounded command line" title="Console"><span>Parser-backed commands only. No arbitrary JavaScript, text decisions, or simulation operation is accepted.</span></Heading><article className="console-card command-card"><form onSubmit={(event) => { event.preventDefault(); void execute() }}><label htmlFor="qcg-command-line">Command<input id="qcg-command-line" value={line} maxLength={160} onChange={(event) => setLine(event.target.value)} placeholder="help" autoComplete="off" /></label><button className="primary" type="submit">Run bounded command</button></form><ol className="command-output" aria-live="polite">{output.length ? output.map((message, index) => <li key={`${index}-${message}`}>{message}</li>) : <li>Type <code>help</code> for the finite grammar.</li>}</ol></article></>
}
function WebMcpView(props: ViewProps) { return <><Heading kicker="bounded public surface" title="WebMCP"><span>Exactly four quantum tools are registered; collaboration uses the separate DevTools bridge.</span></Heading><article className="console-card"><dl className="console-facts"><dt>Availability</dt><dd>{props.supported ? 'available' : 'unavailable'}</dd><dt>Registration</dt><dd>{props.registrationStatus}</dd><dt>Tools</dt><dd>{props.toolNames.length}</dd></dl><ul className="tool-list">{props.toolNames.map((name) => <li key={name}><span className="status-pip success" /><code>{name}</code></li>)}</ul></article></> }
function DecisionsView(props: ViewProps) { const [justification, setJustification] = useState(''); const recommendation = props.state.recommendation; const canSimulate = props.state.authority_state === 'authorized' && recommendation?.decision === 'simulate_first'; return <><Heading kicker="human authority" title="Decisions" tone="authority"><span>Only a human button can apply a disposition. Agents can propose, never authorize.</span></Heading>{!recommendation ? <Empty title="No active recommendation" action={() => props.setView('inspector')} label="Open Inspector" /> : <div className="console-grid two"><article className="console-card authority-card"><h2>{recommendation.decision.replaceAll('_', ' ')}</h2><p className="muted">{recommendation.reason_codes.join(' · ')}</p><label>Human justification<textarea value={justification} maxLength={500} onChange={(event) => setJustification(event.target.value)} placeholder="Override requires 12 characters." /></label><div className="button-row"><button className="primary" disabled={props.busy} onClick={() => props.recordDecision('accepted', justification)}>Accept</button><button disabled={props.busy} onClick={() => props.recordDecision('deferred', justification)}>Defer</button><button className="danger" disabled={props.busy || justification.trim().length < 12} onClick={() => props.recordDecision('overridden', justification)}>Override</button></div></article><article className="console-card"><h2>Bounded execution</h2><p>Simulation is website-only and unavailable through the DevTools or sidepanel transports.</p><dl className="console-facts"><dt>Authority</dt><dd>{props.state.authority_state}</dd><dt>Local simulations</dt><dd>{props.state.effects.local_simulations}</dd></dl>{canSimulate && <div className="button-row"><button className="primary" disabled={props.busy} onClick={props.runSimulation}>Run bounded local simulation</button><button disabled={props.busy} onClick={props.revokeConsent}>Revoke consent</button></div>}</article></div>}</> }
function SourcesView() { return <><Heading kicker="provenance rail" title="Sources"><span>Inspection capabilities are explicit. Static profiles never offer simulation.</span></Heading><article className="console-card"><table><thead><tr><th>Profile</th><th>Formats</th><th>Capability</th></tr></thead><tbody>{quantumAdapters.map((item) => <tr key={item.id}><td>{item.label}</td><td>{item.extensions.join(', ')}</td><td>{item.capabilities.simulate ? 'inspect / compile / simulate' : 'inspect only'}</td></tr>)}</tbody></table></article><p className="notice">The sanitized console snapshot carries profile facts and digests only; raw source is never exported.</p></> }
function ReceiptsView(props: ViewProps) { return <><Heading kicker="portable proof" title="Receipts" tone="evidence"><span>Evidence binds artifact digest, recommendation, human disposition and measured effects.</span></Heading>{!props.state.receipt ? <Empty title="No receipt yet" action={() => props.setView('inspector')} label="Run a preflight" /> : <div className="console-grid two"><article className="console-card evidence-card"><dl className="console-facts"><dt>Schema</dt><dd>{props.state.receipt.schema_version}</dd><dt>Receipt</dt><dd>{props.state.receipt.receipt_id}</dd><dt>Digest</dt><dd><code>{short(props.state.receipt.digest)}</code></dd><dt>Stored locally</dt><dd>{props.storedReceipts}</dd></dl></article><article className="console-card"><h2>Export</h2><p>Exports omit source, local paths, secrets, provider errors and credentials.</p><div className="button-row"><button className="primary" disabled={props.busy} onClick={() => props.exportEvidence('json')}>Export JSON</button><button disabled={props.busy} onClick={() => props.exportEvidence('markdown')}>Export Markdown</button></div></article></div>}</> }
function ActivityView(props: ViewProps) { const [message, setMessage] = useState(''); const filtered = props.debugMessages.filter((item) => (props.actorFilter === 'all' || item.actor === props.actorFilter) && (props.kindFilter === 'all' || item.kind === props.kindFilter)); return <><Heading kicker="observable effects" title="Activity"><span>Every preflight and human message is recorded as bounded, attributable activity.</span></Heading><div className="metric-row">{Object.entries(props.state.effects).map(([key, value]) => <article key={key}><b>{value}</b><small>{key.replaceAll('_', ' ')}</small></article>)}</div><p className="notice">Filter: actor=<code>{props.actorFilter}</code> · kind=<code>{props.kindFilter}</code></p><div className="console-grid two"><article className="console-card"><h2>Human collaboration message</h2><textarea value={message} maxLength={500} onChange={(event) => setMessage(event.target.value)} placeholder="Bounded observation; do not paste secrets, paths, or source." /><button className="primary" disabled={!message.trim()} onClick={() => { props.humanMessage(message.trim()); setMessage('') }}>Record human message</button></article><article className="console-card"><h2>Ledger</h2><ol className="activity-list">{props.state.invocations.length ? props.state.invocations.map((item) => <li key={item.id}><b>{item.status}</b> <code>{item.tool}</code><span>{item.summary}</span></li>) : <li>No invocation yet.</li>}</ol></article></div><article className="console-card"><h2>Collaboration messages</h2><ol className="activity-list">{filtered.length ? filtered.map((item) => <li key={item.event_id}><b>{item.actor} · {item.kind}</b><span>{item.summary}</span></li>) : <li>No collaboration messages match this bounded filter.</li>}</ol></article>{props.state.error && <p className="notice error" role="alert">{props.state.error}</p>}</> }
function Empty({ title, action, label }: { title: string; action(): void; label: string }) { return <section className="empty"><h2>{title}</h2><button onClick={action}>{label}</button></section> }
