import { useState, type ReactNode } from 'react'
import { bellOpenQasmProgram, bellProgram, demoCards } from '../catalog'
import { getQuantumAdapter, quantumAdapters } from '../quantumAdapters'
import type { QcgDebugMessage } from '../debugContracts'
import type { HumanChoice, QcgState, QuantumProfileId } from '../types'
import type { ConsoleView } from './contracts'

const short = (value?: string) => value ? `${value.slice(0, 12)}…${value.slice(-8)}` : '—'
const download = (name: string, content: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }

export function ConsoleInspector({ state }: { state: QcgState }) {
  return <><h2>State inspector</h2><dl className="console-facts"><dt>Phase</dt><dd>{state.phase}</dd><dt>Authority</dt><dd>{state.authority_state}</dd><dt>Artifact</dt><dd><code>{short(state.manifest?.artifact_digest)}</code></dd><dt>Recommendation</dt><dd>{state.recommendation?.decision.replaceAll('_', ' ') ?? 'pending'}</dd><dt>Receipt</dt><dd><code>{short(state.receipt?.digest)}</code></dd><dt>QPU submissions</dt><dd>{state.effects.qpu_submissions} (disabled)</dd></dl><p className="muted">This surface contains evidence identifiers, not source, consent tokens, or provider credentials.</p></>
}

export function ConsoleViews(props: {
  view: ConsoleView; state: QcgState; selected: string; select(card: string): void; artifactProfileId: QuantumProfileId; setArtifactProfileId(id: QuantumProfileId): void; busy: boolean
  runDemo(): void; importArtifact(file: File): void; inspectImported(): void; setView(view: ConsoleView): void; recordDecision(choice: HumanChoice, justification: string): void; runSimulation(): void; revokeConsent(): void
  exportEvidence(format: 'json' | 'markdown'): void; toolNames: string[]; registrationStatus: string; supported: boolean; debugMessages: QcgDebugMessage[]; humanMessage(summary: string): void; storedReceipts: number
}) {
  const { view } = props
  if (view === 'inspector') return <InspectorView {...props} />
  if (view === 'console') return <PaletteView {...props} />
  if (view === 'webmcp') return <WebMcpView {...props} />
  if (view === 'decisions') return <DecisionsView {...props} />
  if (view === 'sources') return <SourcesView {...props} />
  if (view === 'receipts') return <ReceiptsView {...props} />
  return <ActivityView {...props} />
}

function Heading({ kicker, title, children }: { kicker: string; title: string; children: ReactNode }) { return <header className="view-heading"><p>{kicker}</p><h1>{title}</h1>{children}</header> }
function InspectorView(props: Parameters<typeof ConsoleViews>[0]) {
  const adapter = getQuantumAdapter(props.artifactProfileId)!
  return <>
    <Heading kicker="01 / bounded input" title="Inspector"><span>Import stays in browser memory; only bounded evidence crosses surfaces.</span></Heading>
    <div className="console-grid two">
      <article className="console-card"><h2>Artifact intake</h2>
        <label>Quantum profile<select value={props.artifactProfileId} onChange={(event) => props.setArtifactProfileId(event.target.value as QuantumProfileId)}>{quantumAdapters.map((item) => <option key={item.id} value={item.id}>{item.label} · {item.executable ? 'local executable' : 'inspection only'}</option>)}</select></label>
        <p className="muted">{adapter.extensions.join(', ')} · 128 KiB maximum · {adapter.capabilities.simulate ? 'simulation capable' : 'static only'}</p>
        <input aria-label="Quantum artifact file" type="file" accept={`${adapter.extensions.join(',')},text/plain`} disabled={props.busy} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) props.importArtifact(file) }} />
        <div className="button-row"><button onClick={() => download('qcg-bell.qs', bellProgram, 'text/plain')}>Q# Bell</button><button onClick={() => download('qcg-bell.qasm', bellOpenQasmProgram, 'text/plain')}>OpenQASM Bell</button><button disabled={props.busy || props.state.manifest?.provenance !== 'human_import'} onClick={props.inspectImported}>Inspect import</button></div>
      </article>
      <article className="console-card"><h2>Frozen decision cards</h2><div className="fixture-list">{demoCards.map((card) => <button className={props.selected === card.id ? 'selected' : ''} key={card.id} onClick={() => props.select(card.id)}><b>{card.title}</b><small>{card.detail}</small></button>)}</div><button className="primary wide" disabled={props.busy} onClick={props.runDemo}>Run selected preflight</button></article>
    </div>
    {props.state.manifest && <article className="console-card"><h2>Current artifact</h2><dl className="console-facts"><dt>File</dt><dd>{props.state.manifest.file_name}</dd><dt>Profile</dt><dd>{props.state.manifest.artifact_profile}</dd><dt>Format</dt><dd>{props.state.manifest.format}</dd><dt>Digest</dt><dd><code>{short(props.state.manifest.artifact_digest)}</code></dd><dt>Compiler</dt><dd>{props.state.manifest.compiler.status}</dd></dl></article>}
  </>
}
function PaletteView(props: Parameters<typeof ConsoleViews>[0]) { return <><Heading kicker="safe command palette" title="Console"><span>Finite buttons only. This palette never accepts arbitrary code or executes a simulation.</span></Heading><div className="palette"><button disabled={props.busy} onClick={props.runDemo}>Run selected preflight</button><button disabled={props.busy || !props.state.manifest} onClick={props.inspectImported}>Inspect current artifact</button><button onClick={() => props.setView('decisions')}>Open human decisions</button><button onClick={() => props.setView('receipts')}>Open evidence receipt</button><button onClick={() => props.setView('activity')}>Open activity ledger</button></div><p className="notice">Safe command surface: intent is reviewed, human authority is explicit, and local simulation remains a website-only action.</p></> }
function WebMcpView(props: Parameters<typeof ConsoleViews>[0]) { return <><Heading kicker="bounded public surface" title="WebMCP"><span>Exactly four quantum tools are registered; collaboration uses the separate DevTools bridge.</span></Heading><article className="console-card"><dl className="console-facts"><dt>Availability</dt><dd>{props.supported ? 'available' : 'unavailable'}</dd><dt>Registration</dt><dd>{props.registrationStatus}</dd><dt>Tools</dt><dd>{props.toolNames.length}</dd></dl><ul className="tool-list">{props.toolNames.map((name) => <li key={name}><code>{name}</code></li>)}</ul></article></> }
function DecisionsView(props: Parameters<typeof ConsoleViews>[0]) { const [justification, setJustification] = useState(''); const recommendation = props.state.recommendation; const canSimulate = props.state.authority_state === 'authorized' && recommendation?.decision === 'simulate_first'; return <><Heading kicker="human authority" title="Decisions"><span>Only a human button can apply a disposition. Agents can propose, never authorize.</span></Heading>{!recommendation ? <Empty title="No active recommendation" action={() => props.setView('inspector')} label="Open Inspector" /> : <div className="console-grid two"><article className="console-card"><h2>{recommendation.decision.replaceAll('_', ' ')}</h2><p className="muted">{recommendation.reason_codes.join(' · ')}</p><label>Human justification<textarea value={justification} maxLength={500} onChange={(event) => setJustification(event.target.value)} placeholder="Override requires 12 characters." /></label><div className="button-row"><button className="primary" disabled={props.busy} onClick={() => props.recordDecision('accepted', justification)}>Accept</button><button disabled={props.busy} onClick={() => props.recordDecision('deferred', justification)}>Defer</button><button className="danger" disabled={props.busy || justification.trim().length < 12} onClick={() => props.recordDecision('overridden', justification)}>Override</button></div></article><article className="console-card"><h2>Bounded execution</h2><p>Simulation is website-only and unavailable through the DevTools or sidepanel transports.</p><dl className="console-facts"><dt>Authority</dt><dd>{props.state.authority_state}</dd><dt>Local simulations</dt><dd>{props.state.effects.local_simulations}</dd></dl>{canSimulate && <div className="button-row"><button className="primary" disabled={props.busy} onClick={props.runSimulation}>Run bounded local simulation</button><button disabled={props.busy} onClick={props.revokeConsent}>Revoke consent</button></div>}</article></div>}</> }
function SourcesView(props: Parameters<typeof ConsoleViews>[0]) { return <><Heading kicker="provenance rail" title="Sources"><span>Inspection capabilities are explicit. Static profiles never offer simulation.</span></Heading><article className="console-card"><table><thead><tr><th>Profile</th><th>Formats</th><th>Capability</th></tr></thead><tbody>{quantumAdapters.map((item) => <tr key={item.id}><td>{item.label}</td><td>{item.extensions.join(', ')}</td><td>{item.capabilities.simulate ? 'inspect / compile / simulate' : 'inspect only'}</td></tr>)}</tbody></table></article><p className="notice">The sanitized console snapshot carries profile facts and digests only; raw source is never exported.</p></> }
function ReceiptsView(props: Parameters<typeof ConsoleViews>[0]) { return <><Heading kicker="portable proof" title="Receipts"><span>Evidence binds artifact digest, recommendation, human disposition and measured effects.</span></Heading>{!props.state.receipt ? <Empty title="No receipt yet" action={() => props.setView('inspector')} label="Run a preflight" /> : <div className="console-grid two"><article className="console-card"><dl className="console-facts"><dt>Schema</dt><dd>{props.state.receipt.schema_version}</dd><dt>Receipt</dt><dd>{props.state.receipt.receipt_id}</dd><dt>Digest</dt><dd><code>{short(props.state.receipt.digest)}</code></dd><dt>Stored locally</dt><dd>{props.storedReceipts}</dd></dl></article><article className="console-card"><h2>Export</h2><p>Exports omit source, local paths, secrets, provider errors and credentials.</p><div className="button-row"><button className="primary" disabled={props.busy} onClick={() => props.exportEvidence('json')}>Export JSON</button><button disabled={props.busy} onClick={() => props.exportEvidence('markdown')}>Export Markdown</button></div></article></div>}</> }
function ActivityView(props: Parameters<typeof ConsoleViews>[0]) { const [message, setMessage] = useState(''); return <><Heading kicker="observable effects" title="Activity"><span>Every preflight and human message is recorded as bounded, attributable activity.</span></Heading><div className="metric-row">{Object.entries(props.state.effects).map(([key, value]) => <article key={key}><b>{value}</b><small>{key.replaceAll('_', ' ')}</small></article>)}</div><div className="console-grid two"><article className="console-card"><h2>Human collaboration message</h2><textarea value={message} maxLength={500} onChange={(event) => setMessage(event.target.value)} placeholder="Bounded observation; do not paste secrets, paths, or source." /><button className="primary" disabled={!message.trim()} onClick={() => { props.humanMessage(message.trim()); setMessage('') }}>Record human message</button></article><article className="console-card"><h2>Ledger</h2><ol className="activity-list">{props.state.invocations.length ? props.state.invocations.map((item) => <li key={item.id}><b>{item.status}</b> <code>{item.tool}</code><span>{item.summary}</span></li>) : <li>No invocation yet.</li>}</ol></article></div><article className="console-card"><h2>Collaboration messages</h2><ol className="activity-list">{props.debugMessages.length ? props.debugMessages.map((item) => <li key={item.event_id}><b>{item.actor} · {item.kind}</b><span>{item.summary}</span></li>) : <li>No collaboration messages yet.</li>}</ol></article>{props.state.error && <p className="notice error" role="alert">{props.state.error}</p>}</> }
function Empty({ title, action, label }: { title: string; action(): void; label: string }) { return <section className="empty"><h2>{title}</h2><button onClick={action}>{label}</button></section> }
